# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /app

# Install Git (if not already installed)
RUN apt-get update && apt-get install -y git

# Clone your Git repository
RUN git clone https://github.com/jonkan999/evntblx-main.git /app

# Install any needed packages specified in requirements.txt
RUN pip install -r venues/python/requirements.txt  # If you have any dependencies

# Run your Python script when the container launches
CMD ["python", "venues/python/docker_scripts/generate_venue_boxes.py"]
